#!/usr/bin/env python

import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[0]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip();

if re.match(r"^(dev|main)$", branch):
	print("ERROR! You cannot push directly to main or dev, only merge through pull request")
	sys.exit(1)
    
